# Generated by Django 2.0.6 on 2019-01-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='tajam_pendengaran',
            field=models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='tajam_penglihatan',
            field=models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=9, null=True),
        ),
    ]
