# Generated by Django 2.0.6 on 2018-06-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapemeriksaan',
            name='imported_file',
            field=models.BooleanField(default=False),
        ),
    ]
