# Generated by Django 2.0.6 on 2018-06-22 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0002_datapemeriksaan_imported_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaan',
            name='dari_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='puskesmas_app.DataPemeriksaan'),
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='migrasi_dari_excel',
            field=models.BooleanField(default=False),
        ),
    ]
