# Generated by Django 2.0.6 on 2018-06-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0003_auto_20180622_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='asma_diri',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='asma_keluarga',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='diabetes_diri',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='diabetes_keluarga',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='hipertensi_diri',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='hipertensi_keluarga',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='kanker_diri',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='kanker_keluarga',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='kolestrol_tinggi_diri',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='kolestrol_tinggi_keluarga',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='konsumsi_alkohol',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='kurang_aktifitas_fisik',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='kurang_sayur_dan_buah',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='merokok',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='penyakit_jantung_diri',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='penyakit_jantung_keluarga',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='stroke_diri',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='stroke_keluarga',
            field=models.NullBooleanField(),
        ),
    ]
