# Generated by Django 2.0.6 on 2018-06-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0004_auto_20180622_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='berat_badan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='diastol',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='lingkar_perut',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='sistol',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='tinggi_badan',
            field=models.IntegerField(null=True),
        ),
    ]
