# Generated by Django 2.0.6 on 2018-06-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0005_auto_20180622_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='dari_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puskesmas_app.DataPemeriksaan'),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='pasien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='puskesmas_app.Pasien'),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='tanggal',
            field=models.DateField(null=True),
        ),
    ]
