# Generated by Django 2.0.6 on 2018-06-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0006_auto_20180622_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='berat_badan',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='diastol',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='lingkar_perut',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='pengukuran_fungsi_paru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='sistol',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='tinggi_badan',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
