# Generated by Django 2.0.6 on 2018-06-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0008_auto_20180622_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='status',
            field=models.CharField(choices=[('Menikah', 'Menikah'), ('Belum', 'Belum'), ('Janda/Duda', 'Janda/Duda'), ('None', 'Gak Jelas')], max_length=20),
        ),
    ]
