# Generated by Django 2.0.6 on 2018-06-25 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0009_auto_20180622_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='demografipenduduk',
            name='tahun',
            field=models.PositiveIntegerField(default=2018, help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2018)]),
            preserve_default=False,
        ),
    ]
