# Generated by Django 2.0.6 on 2018-06-25 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0010_demografipenduduk_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demografipenduduk',
            name='tahun',
            field=models.PositiveIntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017)], help_text='Gunakan Format Tahun: <YYYY>', validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2018)]),
        ),
    ]
