# Generated by Django 2.0.6 on 2018-06-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0012_auto_20180625_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='iva',
            field=models.NullBooleanField(choices=[(None, ''), (True, 'Positif'), (False, 'Negatif')]),
        ),
    ]
