# Generated by Django 2.0.6 on 2018-06-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0013_auto_20180625_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='penyuluhan_iva_and_cbe',
            field=models.NullBooleanField(choices=[(None, ''), (True, 'Ikut'), (False, 'Tidak Ikut')]),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='penyuluhan_potensi_cedera',
            field=models.NullBooleanField(choices=[(None, ''), (True, 'Ikut'), (False, 'Tidak Ikut')]),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='penyuluhan_rokok',
            field=models.NullBooleanField(choices=[(None, ''), (True, 'Ikut'), (False, 'Tidak Ikut')]),
        ),
    ]
