# Generated by Django 2.0.6 on 2018-06-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0014_auto_20180625_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='benjolan_payudara',
            field=models.NullBooleanField(choices=[(None, ''), (True, 'Ditemukan'), (False, 'Tidak Ditemukan')]),
        ),
    ]
