# Generated by Django 2.0.6 on 2018-06-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0016_auto_20180625_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaan',
            name='gangguan_mental_emosional',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='tajam_pendengaran',
            field=models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='tajam_penglihatan',
            field=models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=9, null=True),
        ),
    ]
