# Generated by Django 2.0.6 on 2018-07-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0025_auto_20180704_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaan',
            name='indeks_masa_tubuh',
            field=models.IntegerField(null=True),
        ),
    ]
