# Generated by Django 2.0.6 on 2018-07-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0026_pemeriksaan_indeks_masa_tubuh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='indeks_masa_tubuh',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
