# Generated by Django 2.0.6 on 2018-07-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0027_auto_20180717_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='indeks_masa_tubuh',
            field=models.FloatField(null=True),
        ),
    ]
