# Generated by Django 2.0.6 on 2018-07-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas_app', '0028_auto_20180717_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaan',
            name='umur',
            field=models.IntegerField(null=True),
        ),
    ]
