# Generated by Django 2.0.6 on 2018-06-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='embarked',
            field=models.CharField(choices=[('C', 'Cherbourg'), ('Q', 'Queenstown'), ('S', 'Southampton')], max_length=1),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='sex',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1),
        ),
    ]
