# Generated by Django 2.0.6 on 2018-06-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafik', '0002_auto_20180625_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='kecamatan',
            field=models.CharField(choices=[('Karang Pilang', (('karang_pilang', 'Karang Pilang'), ('kabraon', 'Kebraon'), ('kedurus', 'Kedurus'), ('warugunung', 'Warugunung'))), ('Jambangan', (('jambangan', 'Jambangan'), ('karah', 'Karah'), ('kebonsari', 'Kebonsari'), ('pagesangan', 'Pagesangan')))], max_length=30, null=True),
        ),
    ]
