# Generated by Django 2.0.6 on 2018-06-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafik', '0004_auto_20180629_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='kecamatan',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='sex',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=10),
        ),
    ]
